-- MySQL Script generated by MySQL Workbench
-- Wed Sep 16 06:10:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema main
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema main
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `main` DEFAULT CHARACTER SET utf8;
USE `main`;

-- -----------------------------------------------------
-- Table `main`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`users`
(
    `id`       INT UNSIGNED NOT NULL,
    `login`    VARCHAR(45)  NOT NULL,
    `name`     VARCHAR(45)  NOT NULL,
    `avatar`   BLOB         NOT NULL,
    `passHash` BLOB         NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`data`
(
    `id`     INT UNSIGNED NOT NULL,
    `date`   TIMESTAMP    NOT NULL,
    `query`  VARCHAR(45)  NOT NULL,
    `pic`    BLOB         NOT NULL,
    `userId` INT          NOT NULL,
    PRIMARY KEY (`id`, `userId`),
    UNIQUE INDEX `id` (`id` ASC) VISIBLE,
    INDEX `userId` (`userId` ASC) VISIBLE,
    CONSTRAINT `userId`
        FOREIGN KEY (`userId`)
            REFERENCES `main`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
